package com.charity.util;

public final class Constants {
	public static final String CURRENT_USER_SESSION_ATTRIBUTE = "CURRENT_USER_SESSION_ATTRIBUTE";
	public static final String CACHE_NAME_ALL_BRANCHES = "ALL_BRANCHES_CACHE";
	public static final String CACHE_NAME_ALL_COUPONS = "ALL_COUPONS_CACHE";
	public static final long UAE_COUNTRY_ID = 1l;
	public static final long ALL_BRANCHES_ID = 1l;
	public static final long DEFAULT_EMARAH_ID = 6l;

	public static final int TOKEN_EXPIRATION_MINUTES = 60 * 24 * 1000;
	public static final String CACHE_NAME_ERROR_CODE = "ERROR_CODE_CACHE";
	public static final String CACHE_NAME_NEW_PROJECT_TYPE = "NEW_PROJECT_TYPE_CACHE";
	public static final String CACHE_NAME_COUPONS_TYPES = "COUPON_TYPE_CACHE";
	public static final String CACHE_NAME_COUPON_IMAGE = "COUPON_IMAGE_CACHE";
	public static final String CACHE_NAME_ALL_COUNTRIES = "ALL_COUNTRIES_CACHE";
	public static final String CACHE_NAME_ALL_GENDERS = "ALL_GENDERS_CACHE";
	public static final String CACHE_NAME_ALL_PROJECT_CATEGORIES = "ALL_PROJECT_CATEGORIES_CACHE";
	public static final String CACHE_NAME_PROJECT_TYPE_COUNTRIES = "PROJECT_TYPE_COUNTRIES_CACHE";
	// public static final String CACHE_NAME_OLD_PROJECTS_FOR_DONATOR =
	// "OLD_PROJECTS_FOR_DONATOR_CACHE";
	public static final String CACHE_NAME_SPONSORSHIP_TYPE = "SPONSORSHIP_TYPE_CACHE";
	public static final String CACHE_NAME_COUNTRY_SPONSORSHIP = "COUNTRY_SPONSORSHIP_CACHE";
	public static final String CACHE_NAME_GIFT_TYPE = "GIFT_TYPE_CACHE";
	public static final String CACHE_NAME_FIRST_TITLE = "FIRST_TITLE_CACHE";
	public static final String CACHE_NAME_HAJJ_FIRST_TITLE = "HAJJ_FIRST_TITLE_CACHE";
	public static final String CACHE_NAME_HAJJ_LAST_TITLE = "HAJJ_LAST_TITLE_CACHE";
	public static final String CACHE_NAME_COLLECTORS = "COLLECTORS_CACHE";
	public static final String CACHE_NAME_LAST_TITLE = "LAST_TITLE_CACHE";
	public static final String CACHE_NAME_SPONSORSHIP_PAYMENT_TYPE = "SPONSORSHIP_PAYMENT_TYPE_CACHE";
	public static final String CACHE_NAME_BANKS_CHEQUE = "BANKS_CHEQUE_CACHE";
	public static final String CACHE_NAME_NATIONALITIES = "NATIONALITIES_CACHE";
	public static final String CACHE_NAME_BANKS_TRANSFER = "BANKS_TRANSFER_CACHE";
	public static final String CACHE_NAME_COUNTRY_IMAGE = "COUNTRY_IMAGE_CACHE";
	public static final String CACHE_NAME_COUNTRY_SPONSORSHIP_IMAGE = "COUNTRY_SPONSORSHIP_IMAGE_CACHE";
	public static final String CACHE_NAME_NEW_PROJECT_TYPE_IMAGE = "NEW_PROJECT_TYPE_IMAGE_CACHE";
	public static final String CACHE_NAME_CHARITY_BOX_STATUS = "CHARITY_BOX_STATUS_CACHE";
	public static final String CACHE_NAME_CHARITY_BOX_TYPE = "CHARITY_BOX_TYPE_CACHE";
	public static final String CACHE_NAME_CHARITY_BOX_CATEGORY = "CHARITY_BOX_CATEGORY_CACHE";
	public static final String CACHE_NAME_CHARITY_BOX_REGION = "CHARITY_BOX_REGION_CACHE";
	public static final String CACHE_NAME_CHARITY_BOX_LOCATION = "CHARITY_BOX_LOCATION_CACHE";
	public static final String CACHE_NAME_CHARITY_BOX_SUB_LOCATION = "CHARITY_BOX_SUB_LOCATION_CACHE";
	public static final String CACHE_NAME_CHARITY_BOX_ACTION_TYPE = "CHARITY_BOX_ACTION_TYPE_CACHE";
	public static final String CACHE_NAME_EMARAH = "EMARAH_CACHE";
	public static final String CACHE_NAME_SPONSORSHIP_TYPE_IMAGE = "SPONSORSHIP_TYPE_IMAGE_CACHE";
	public static final String CACHE_NAME_COMMUNICATION_TYPE = "COMMUNICATION_TYPE_CACHE";

}
