package com.charity.enums;

public enum RoleTypeEnum {

	ROLE_ADMIN(1l, "ROLE_ADMIN"), ROLE_EMPLOYEE(2l, "ROLE_EMPLOYEE"), ROLE_DELEGATE(3l, "ROLE_DELEGATE"),
	ROLE_BENEFACTOR(4l, "ROLE_BENEFACTOR"), ROLE_TRACK_DELEGATES(5l, "ROLE_TRACK_DELEGATES"),
	ROLE_MANAGE_DELEGATES(6l, "ROLE_MANAGE_DELEGATES"), ROLE_MANAGE_EMPLOYEES(7l, "ROLE_MANAGE_EMPLOYEES"),
	ROLE_COLLECT_MONEY(8l, "ROLE_COLLECT_MONEY"), ROLE_DEPOSIT_FINANCE(9l, "ROLE_DEPOSIT_FINANCE"),
	ROLE_CREATE_MANUAL_RECEIPT(10l, "ROLE_CREATE_MANUAL_RECEIPT"), ROLE_MANAGE_COUPONS(11l, "ROLE_MANAGE_COUPONS"),
	ROLE_REPORT_COUPONS_INCOME(12l, "ROLE_REPORT_COUPONS_INCOME"),
	ROLE_REPORT_DELEGATES_INCOME(13l, "ROLE_REPORT_DELEGATES_INCOME"),
	ROLE_REPORT_LOCATIONS_INCOME(14l, "ROLE_REPORT_LOCATIONS_INCOME"),
	ROLE_REPORT_COLLECTION_DELEGATES(15l, "ROLE_REPORT_COLLECTION_DELEGATES"),
	ROLE_REPORT_FINANCE_DEPOSIT(16l, "ROLE_REPORT_FINANCE_DEPOSIT"), ROLE_MANAGE_SETTINGS(17l, "ROLE_MANAGE_SETTINGS"),
	ROLE_REPORT_BENEFACTORS(18l, "ROLE_REPORT_BENEFACTORS");

	private String name;
	private Long id;

	private RoleTypeEnum(Long id, String name) {
		this.name = name;
		this.id = id;
	}

	public Long getId() {
		return id;
	}

	public String getName() {
		return name;
	}

}
